posicao = ( 'Palmeiras', 'Internacional', 'Fluminense', 'Corinthians', 'Flamengo', 'Athletico-PR', 'Atlético-MG', 'Fortaleza', 'São paulo', 'América-MG', 'Botafogo', 'Santos', 'Goiás', 'Bragantino', 'Coritiba', 'Cuiabá', 'Ceará', 'Atlético Goianiense', 'Aval', 'Juventude')
print(' Lista dos times:',posicao)
print('='*30)
print(' Os primeitos colocado são:',posicao[0:5])
print('='*30)
print(' Os quatro últimos são:',posicao[16:])
print('='*30)
print('A lista em ordem alfabética:',sorted(posicao))
print('='*30)
print(' Chapecoense não está na lista')#posicao.index('Chapecoense'))